@host = http://127.0.0.1:5000/

###Create Account
POST {{host}}/accounts
Content-Type: application/json

{
    "firstname" : "user",
    "lastname" : "number2"
}


###Add a vehicle
POST {{host}}/vehicle
Content-Type: application/json

{
    "color": "blue",
    "make": "honda",
    "model": "honda beat",
    "plate_number": "123 ABC",
    "owner_id": 1,
    "parking_area_id": null
}

###Gets All vehicles
GET {{host}}/vehicle
Content-Type: application/json

###Update a vehicle
PUT {{host}}/vehicle/3
Content-Type: application/json

{
    "owner_id" : 1,
    "color": "cyan",
    "plate_number": "123 CED"
}

###Remove a vehicle
DELETE {{host}}/vehicle/1
Content-Type: application/json

###Add parking area
POST {{host}}/parkingarea
Content-Type: application/json

{
    "slots": 40
}

###Get all parking area
GET {{host}}/parkingarea
Content-Type: application/json


###Update Parking area
PUT {{host}}/parkingarea/3
Content-Type: application/json

{
    "slots" : 10
}

###Delete a Parking area
DELETE {{host}}/parkingarea/2
Content-Type: application/json